name: Gerar Dados de vendas

on:
  workflow_dispatch:

jobs:
  import_libs_and_run_script_create_sale_data:

    runs-on: ubuntu-latest
    #env:
    #  AWS_DEFAULT_REGION: us-east-1
      
    #permissions:
    #  id-token: write
    #  contents: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install lib pandas
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Install lib numpy
      run: pip install numpy
    - name: Install lib botocore
      run: pip install botocore    
    - name: Install lib boto3
      run: pip install boto3  
    - name: Install lib openpyxl
      run: pip install openpyxl
    - name: Install lib Faker
      run: pip install Faker  
      
    - name: create_fake_data
      run: |
          pwd;ls;python scripts/create_fake_sale_data.py

        
        
    - name: upload tabela csv
      run:  pwd;ls -l;mkdir transferir;cp df_fake.csv transferir; ls transferir
    - uses: actions/upload-artifact@v1
      with:
         name: df_fake.csv
         path: transferir
   #####################################################      
  download_file:
    name: get_cred_and_copy_table_to s3
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      
    permissions:
      id-token: write
      contents: read
    needs: import_libs_and_run_script_create_sale_data
    steps:
     - uses: actions/download-artifact@v1
       with:
          name: df_fake.csv
          path: .
 #         
     - name: get aws credential
       uses: aws-actions/configure-aws-credentials@v1
       with:
          role-to-assume: arn:aws:iam::${{secrets.id}}:role/github-actions-role
          aws-region: ${{env.AWS_DEFAULT_REGION}}    
     - name: copy table to bucket
       run: |
          pwd;ls -l ;aws s3 cp df_fake.csv s3://df-fake-sale-bucket
